### ISSUE TITLE
Unnecessary whitespace for some tags

### ISSUE THREAD

**Issue by djfpaagman** [marcoroth/phlexing#1]
I'm converting some Tailwind UI components with Phlexing and noticed that I get a lot of unnecessary `whitespace` rows in my code. I've narrowed it down a bit and it seems to happen only for certain tags. Here's an example:

```html
<div>
  <label>Test</label>
</div>
```

converts into:

```ruby
div do
  whitespace
  label { "Test" }
end
```

If you change `label` to `div` or `h1` it does not add the `whitespace`.

I've narrowed the cause down to the call to `HtmlPress` here, which leaves a space between the tags: 

https://github.com/marcoroth/phlexing/blob/60df23a71579a5d2d8b238890d12e048b42e1a5f/gem/lib/phlexing/converter.rb#L171

```ruby
irb(main):001:0" html = <<~HTML.strip
irb(main):002:0"   <div>
irb(main):003:0"     <label>Test</label>
irb(main):004:0"  </div>
irb(main):005:0> HTML
=> "<div>\n  <label>Test</label>\n</div>"
irb(main):006:0> HtmlPress.press(html)
=> "<div> <label>Test</label></div>"
         ^ extra space here
```

```ruby
irb(main):007:0" html = <<~HTML.strip
irb(main):008:0"   <div>
irb(main):009:0"     <h1>Test</h1>
irb(main):010:0"   </div>
irb(main):011:0> HTML
=> "<div>\n  <h1>Test</h1>\n</div>"
irb(main):012:0> HtmlPress.press(html)
=> "<div><h1>Test</h1></div>"
         ^ no space here
```

It seems that HtmlPress is unmaintained and marked deprecated by the owner (https://github.com/stereobooster/html_press/issues/21), so I don't really expect them to fix this or accept a fix. 

Not sure what a good approach would be here, what are your thoughts? Happy to work on some kind of fix 👍

**Comment by marcoroth** [comment]
Hey @djfpaagman, thanks for opening this issue!

The whitespaces are actually there on purpose and expected because they are needed in some cases, as it could break some markups (I actually had this happen in one of my cases, that's why I added them 🙈). Sadly that's how HTML Block elements work.

For example:
```html
<div>
  <label>Test</label>
</div>
```
is not equal to:
```html
<div><label>Test</label></div>
```

Maybe we could add a flag to enforce the removal of the whitespaces if you are sure that you don't need them.
