### ISSUE TITLE
Wrong boolean attributes conversion

### ISSUE THREAD

**Issue by stephannv** [marcoroth/phlexing#119]
**ERB Input:**
```erb
<input required>
```

**Output:**
```ruby
input(required: "")
```

**Expected output:**
```ruby
input(required: true)
```

**Comment by marcoroth** [comment]
Thanks for reporting this @stephannv.

I don't think we can really support this, unless we hard code as list of attributes which should get forced to a boolean. Probably something like:

```ruby
BOOLEAN_ATTRIBUTES = ["required", "disabled", "checked", "hidden", "readonly"]
```

But on the other hand, the output Phlexing is providing is not wrong, HTML boolean can either be written as:
```html
<input required>
```

```html
<input required="">
```

or:
```html
<input required="required">
```

All of them are equally valid. [MDN says](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#boolean_attributes):
> If a boolean attribute is present, its value is true, and if it's absent, its value is false.
> To be clear, the values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether. 

So I'm not sure if this should handled here in in Phlex itself. Any thoughts?

**Comment by stephannv** [comment]
I think it's not necessary to map all the possible boolean attributes, because some [js frameworks can create new boolean attributes](https://vuetifyjs.com/en/components/text-fields/#clearable) every day, eg. `<v-input clearable>`. I think this behavior should be simple: if `<tag attribute>` then `tag(attribute: true)`, if `<tag attribute="">` then `tag(attribute: "")`.

I wrote some tests for this behavior:
```ruby
  it "should convert boolean attributes properly" do
    html = %(<input required>)

    expected = <<~PHLEX.strip
      input(required: true)
    PHLEX

    assert_phlex_template expected, html
  end

  it "should convert blank attributes properly" do
    html = %(<input required="">)

    expected = <<~PHLEX.strip
      input(required: "")
    PHLEX

    assert_phlex_template expected, html
  end
```

But Nokogiri `#value` is always returning `""` to `<input required>` and `<input required="">`, so I think this can be unfeasible due to Nokogiri behavior.

**Comment by marcoroth** [comment]
Thanks for providing some test-cases! I think that would make sense.

> But Nokogiri #value is always returning "" to <input required> and <input required="">, so I think this can be unfeasible due to Nokogiri behavior.

Yeah, I guess that's the root cause of the issue. I wonder if there's another method inside Nokogiri we might be able to use for that!

**Comment by stephannv** [comment]
@marcoroth I found a solution, but I don't know if it's the best solution: https://github.com/marcoroth/phlexing/pull/120
