### ISSUE TITLE
SVG tags are a special case

### ISSUE THREAD

**Issue by stephannv** [marcoroth/phlexing#138]
**ERB Input:**
```erb
<svg>
  <feSpecularLighting>
    <fePointLight/>
  </feSpecularLighting>    
</svg>
```

**Output:**
```ruby
svg { fespecularlighting { fepointlight } }
```

**Expected output:**
```ruby
# `el` is just a random name
svg { |el| el.feSpecularLighting { el.fePointLight } }
# or
svg do |el|
  el.feSpecularLighting do 
    el.fePointLight
  end
end
```

There are two problems:
- Phlex uses yielded svg to build svg tags
- SVG tag methods uses camelCase pattern, downcase method names results on NoMethodError

**Comment by marcoroth** [comment]
Oh right, this changed recently! Thanks for the report.

I guess we can add a special case for handling SVG elements in Phlexing
