### ISSUE TITLE
https://phlexing.fun is not reachable

### ISSUE THREAD

**Issue by segiddins** [marcoroth/phlexing#167]
https://phlexing.fun doesn't appear to be up right now

**Comment by marcoroth** [comment]
Hey @segiddins, thanks for the heads-up!

I'm currently fighting with Heroku to get the application back up. Somehow they had issues with charging my credit card and decided to suspend the app. 

I'll let you know when it's back up 🙏🏼

**Comment by marcoroth** [comment]
Okay, looks like we are back up 😅
