### ISSUE TITLE
Copy to clipboard button copies old code, not what is in text box

### ISSUE THREAD

**Issue by bbugh** [marcoroth/phlexing#326]
Sorry, you don't have a bug template, so I'm freestyling.

**Issue**

When clicking the `click->converter#copy` button, what is copied to the clipboard is output from a previous ERB conversion, not the one that is currently in the box. This happens 100% of the time for me since it started previously.

I'm guessing it might have something to do with either not having a component name, or the text input not being valid but the output is still generated, and then it gets "stuck" or something in Turbo. Refreshing the page resolves the issue.

**Potential Solution**

I noticed in the source that it's copying from `output-copy`, a second buffer of the text in the `pre#output` field. 

https://github.com/marcoroth/phlexing/blob/602f445e3ee0dfff4e0e3a36017910d7ee08ac2d/app/javascript/controllers/converter_controller.js#L29

You surely know better than me since you made it, but that seems like it might be unnecessary. The `innerText` of the `pre` element returns the literal text that is visible to the user, which would prevent any mismatch between what is seen and what is copied.

```diff
- await navigator.clipboard.writeText(document.getElementById("output-copy").value) 
+ await navigator.clipboard.writeText(document.getElementById("output").innerText) 
```

**Comment by marcoroth** [comment]
Oh this is weird, thanks for reporting @bbugh! I'll take a look and see if I can apply the diff as you suggested! Thanks

**Comment by marcoroth** [comment]
Hey @bbugh, I put up #331 to try to resolve this. Would you mind testing if that resolves the issue you were seeing too? Thank you! 🙌🏼
