### ISSUE TITLE
`form_with` short-circuits output

### ISSUE THREAD

**Issue by Z2Flow** [marcoroth/phlexing#332]
**ERB Input:**
```erb
<%= form_with(model: @test) do |form| %>
   <h3>Test</h3>
<% end %>
```

**Output:**
```ruby
class Test < Phlex::HTML
  def view_template
  end
end


```

**Expected output:**
```ruby
class Test < Phlex::HTML
  def view_template
     form_with(model: @test) do |form|
    h3 { "Test" }
  end
end
```
It seems the `form_wth` line is the issue.

**Comment by marcoroth** [comment]
I just reverted commit c0ada9c61ada0eca2d925f7bdfa5f1d9658e3ae4. in 45bb76fd1672bba7c382d5ccf0de7ef49ae9f9e1 which upgraded phlex-rails via #329 which should solve this.

**Comment by Z2Flow** [comment]
Thanks Marco—fixed.
