### ISSUE TITLE
Automatically detect Rails helpers

### ISSUE THREAD

**Issue by marcoroth** [marcoroth/phlexing#42]
Using `Phlexing::Converter.idents` we should be able to figure out if the HTML is depending on any Rails helper within the template. If that's the case we could automatically include the right module, delegate the call to the `helpers` object Phlex provides or we could rewrite the Ruby code that we output

**Comment by joeldrapper** [comment]
I wonder if we should perhaps introduce a compatibility mode to `phlex-rails` itself that just includes all the Rails helpers. 🤔 

I’ve been pretty conservative with helpers so far as I think a bunch of them are not really necessary in Phlex world but it might make things simpler to at least provide them as an optional mixin.

**Comment by marcoroth** [comment]
Maybe! But I guess if we can make the converter good enough to automatically "migrate" these calls it's probably better for the long run.
