### ISSUE TITLE
ERB attribute interpolation with one static and one dynamic string

### ISSUE THREAD

**Issue by marcoroth** [marcoroth/phlexing#76]
**ERB Input:**
```erb
<div style="background: <%= blue? ? "blue" : "red" %>"></div>
```

**Output:**
```ruby
div(style: %(FIXME: background: <%= blue? ? "blue" : "red"))
```

**Expected output:**
```ruby
div(style: %(background: #{blue? ? "blue" : "red"}))
```

**Comment by hangsu** [comment]
Just wanted to chime in here and say that I appreciate the `FIXME:` that currently gets inserted!

I think a 100% accurate conversion might not be possible, but having some sort of indication that a line probably didn't convert right is a huge help.

**Comment by marcoroth** [comment]
Yeah, I thought that might be helpful for the time being.

We can definitely solve this so that Phlexing can 100% convert this!

**Comment by marcoroth** [comment]
@hangsu I shipped a fix in #86. I'd love to know if that also worked in your case.

**Comment by hangsu** [comment]
It works for me!

Really great work, thank you so much.

**Comment by marcoroth** [comment]
Awesome, thanks for the feedback!
